Awesome books: a complete website with navigation
ivaan1992/AwesomeBooks pull request #4
Opened 2021-11-27 17:07 UTC by ivaan1992

For this project I: 

- Added style.
- Made dynamic the site.
- Added more code in HTML file.

2021-11-27 17:51 UTC, mikethreels requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Good job implementing the three required sections 👍 however according to the requirements you should Display the current date below the navigation bar. For this requirement, you should use a library - [Luxon](https://moment.github.io/luxon/#/install). See the article [Get the current date and time](https://moment.github.io/luxon/#/tour?id=get-the-current-date-and-time). 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 17:52 UTC, mikethreels commented on script-class.js
> +function displayPage(link) {
- [ ] Good job implementing the three required sections 👍 however according to the requirements you should Display the current date below the navigation bar. For this requirement, you should use a library - [Luxon](https://moment.github.io/luxon/#/install). See the article [Get the current date and time](https://moment.github.io/luxon/#/tour?id=get-the-current-date-and-time).

2021-11-27 23:56 UTC, D4nielJ requested changes
## Hello @ivaan1992, 

Great work on making the changes requested by the previous reviewer(s) 👏

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Happy coding and stay awesome! 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-27 23:56 UTC, D4nielJ commented on index.html
> +            </div> -->
- [ ] Let's remove unused pieces of code as this should not be committed to GitHub, instead, we can use GitHub history anytime if we need to review a previous version of our code. [This is considered a best practice, you can read more about it here.](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md)

2021-11-27 23:56 UTC, D4nielJ commented on index.html
> +  </main>
[OPTIONAL] I think we could add a footer to the webpage indicating the copyright and information about it as shown in the wireframes to the bottom of our page.

For reference:
![image](https://user-images.githubusercontent.com/79114233/143723672-2a9cef3e-af2e-4649-8a6a-02ad007ebb71.png)

2021-11-27 23:56 UTC, D4nielJ commented on script-class.js
> +window.onload = initClock;
- [ ] Good job implementing your own function to add a clock to the page, unfortunately, part of the requirements of this project is that you use an external library to add function to your webpage, in this case, [Luxon.](https://moment.github.io/luxon/#/install) [You can also read more about working with Luxon here.](https://moment.github.io/luxon/#/tour?id=get-the-current-date-and-time)

2021-11-28 01:35 UTC, eri8-9 approved these changes
Hi @ivaan1992 and @gdumani , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- I see that you did the work, well done!

![Felix](https://media.giphy.com/media/hlQeY3PbhH3i/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-29 13:57 UTC, merged